[package]
name = "neural-network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
ndarray = "0.15.6"
ndarray-rand = "0.14.0"
itertools = "0.8"

[profile.dev]
opt-level = 0
debuginfo-level-std = 0
